version: '3'

services:
  cloud_service_app:
    image: 'csapp:latest'
    restart: 'on-failure'
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
    depends_on:
      - 'postgres'

  postgres:
    image: 'postgres'
    restart: 'on-failure'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
